//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_complaint_assign
    {
        public int Aid { get; set; }
        public Nullable<int> Sid { get; set; }
        public Nullable<int> Fid { get; set; }
        public string studentname { get; set; }
        public string facultyname { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string sdepartment { get; set; }
        public string semester { get; set; }
        public string program { get; set; }
        public string complaint_against { get; set; }
        public string Description { get; set; }
        public string facultyresponsibility { get; set; }
    }
}
