//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_faculty
    {
        
        public int fid { get; set; }


        [Required(ErrorMessage = "Required")]
        public string fname { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", ErrorMessage = "Invalid email format")]
        public string femail { get; set; }
        
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Password)]
        public string fpassword { get; set; }
        
        [Required(ErrorMessage = "Required")]
        public string Department { get; set; }
        
        [Required(ErrorMessage = "Required")]
        public string JobResponsibility { get; set; }
    }
}
