//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int Sid { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Sname { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", ErrorMessage = "Invalid email format")]

        public string Email { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<long> Mobile { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Department { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Semester { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Program { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string ComplaintAgainst { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Description { get; set; }
    }
}
